<?php
$telephone = $block->getCustomer()->getCustomAttribute('telephone');
$customerTelephone = $telephone ? $telephone->getValue() : null;
?>

<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Phone Number') ?></span></legend>
    <div class="field regulation">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Telephone') ?></span></label>
        <div class="control">
            <input type="text" name="telephone" id="telephone"
                   value="<?= $block->escapeHtmlAttr($customerTelephone); ?>" title="<?php /* @escapeNotVerified */
            echo __('Telephone') ?>" class="input-text" data-validate="{required:true, 'aureatelabsvalidationrule':true}">
        </div>
    </div>
</fieldset>

<script type="text/x-magento-init">
   {
       "*": {
           "aureatelabsMethod": {
              "param": "paramvalue"
           }
       }
   }
</script>
