<style>
    #testContent {
        height: 250px;
        background: #86de00;
        padding: 50px 0 0 0;
    }

    #testform {
        margin: 0 auto;
        width: 250px;
        height: 200px;
        padding: 20px 0 0 0;
    }

    #testlayout {
        width: 400px;
        margin: 0 auto;
        background: white;
    }

    #email {
        background: #bfe6ff;
        margin-top: 10px;
    }

    #pass {
        background: #bfe6ff;
        margin-top: 15px;
    }

    #login {
        width: 250px;
        margin: 0 0 11px 0;
        background: #328732;
        color: white;
    }

    #testbock {
        text-align: center;
        height: 25px;
    }

    #testbock span {
        color: #8282c1;
    }
</style>
<button id="test">
    <span>test</span>
</button>

<button id="button">
    <span>Magento</span>
</button>

<div id="modal">
    <div class="modal-body-content">
        <p>Hello World</p>
    </div>
</div>


<button id="magenest">
    <span>test form</span>
</button>

<div id="testContent">
    <div id="testlayout">
        <form id="testform">
            <input type="email" id="email"><br>
            <input type="password" id="pass"><br><br>
            <button id="login">Login</button>
            <div id="testbock">
                <span>magento</span>
            </div>
        </form>
    </div>
</div>

<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ], function ($, modal) {
        $(document).on("click", "#test", function () {
            alert("Helo");
        })

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Magenest',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };
        var popup = modal(options, $('#modal'));
        $('#button').click(function () {
            $('#modal').modal('openModal');
        });

        var test = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'Modal Login',
            buttons: []

        };

        var popup = modal(test, $('#testContent'));
        $("#magenest").on('click', function () {
            $('#testContent').modal('openModal');
        });
    });
</script>
