<?php
/** @var \Magenest\Movie\Block\Showdata $block */
$movie = $block->getMovie();
?>

<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('Name') ?></th>
            <th scope="col" class="col discription"><?php echo __('Discription') ?></th>
            <th scope="col" class="col rating"><?php echo __('Rating') ?></th>
            <th scope="col" class="col director"><?php echo __('DirectorName') ?></th>
            <th scope="col" class="col actor"><?php echo __('ActorName') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($movie as $item): ?>
            <tr>
                <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                    <?php echo $item->getId() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col name">
                    <?php echo $item->getName() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Rating')) ?>" class="col rating">
                    <?php echo $item->getDescription() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Rating')) ?>" class="col rating">
                    <?php echo $item->getRating() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('Description')) ?>" class="col director">
                    <?php echo $item->getDirector() ?>
                </td>
                <td data-th="<?= $block->escapeHtml(__('ActorName')) ?>" class="col actor">
                    <?php echo $item->getActor() ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

